### ISSUE TITLE
Is there a build on Docker Hub for CentOS 7 ?

### ISSUE THREAD

**Issue by cwolfinger** [jdeathe/centos-ssh#134]
I noticed that there is a CentOS 7 branch but no build on docker hub.

**Comment by jdeathe** [comment]
@cwolfinger Yes the branch is ready but I need to make changes to the README and description to indicate the different Dockerfiles and docker tags for the different branches/versions. Once I have figured out how I am going to do that I will tag version 2.0.0 for which there is a build task ready on the Docker hub.

I expect I will create a new development branch for the centos-6 branch called something like centos-6-develop and then merge the centos-7 branch into the master branch.

**Comment by jdeathe** [comment]
@cwolfinger 2.0.0 is now tagged and the latest, centos-7 and centos-7-2.0.0 tags are built on the Docker hub.
- https://github.com/jdeathe/centos-ssh/releases/tag/2.0.0
- https://hub.docker.com/r/jdeathe/centos-ssh/tags/
