### ISSUE TITLE
Need a license file

### ISSUE THREAD

**Issue by cawallin** [jdeathe/centos-ssh#2]
I'm interested in using this docker image, but it's unclear what license it's offered under.  I see that Docker recommends that you have a license in the repo: http://docs.docker.com/docker-hub/official_repos/#license

**Comment by jdeathe** [comment]
Thanks for pointing this out. I will look into it and get one added.

**Comment by jdeathe** [comment]
MIT License added. 

CentOS and it's individual packages have their own licensing Ref:
- http://mirrors.ukfast.co.uk/sites/ftp.centos.org/6.6/os/x86_64/EULA
- http://mirrors.ukfast.co.uk/sites/ftp.centos.org/6.6/os/x86_64/GPL

**Comment by cawallin** [comment]
Thanks!
