### ISSUE TITLE
Consider installing rsync as a package

### ISSUE THREAD

**Issue by dol** [jdeathe/centos-ssh#364]
I use your image to start a userland SSH process to sync two workstations. I perform the sync by running a SSH daemon on one machine and rsync the files from the other machine.

Due to the lack of rsync installed in the image I had to install rsync manually. It would be useful if the rsync package is installed in the base image.

**Comment by jdeathe** [comment]
@dol This image is specifically for an SSH service. I suggest building your own image to meet your requirements of `rsync` that sources from this image. Let me know if you need any help on how to achieve this.

**Comment by dol** [comment]
@jdeathe I don't have any issue to base of you image. I'll do that.
