### ISSUE TITLE
Multiple SSH_USER and SSH_AUTHORIZED_KEYS

### ISSUE THREAD

**Issue by naisanza** [jdeathe/centos-ssh#455]
Is it possible to create multiple `SSH_USER` accounts with multiple `SSH_AUTHORIZED_KEYS`?

**Comment by jdeathe** [comment]
@naisanza Only a single user can be defined with `SSH_USER`. It is possible to set multiple public SSH keys using `SSH_AUTHORIZED_KEYS`, each key must be on a new line or the value should be encoded as a base64 string.

There's nothing stopping you adding new users using the first account but I don't have any use case for creating multiple users.

**Comment by naisanza** [comment]
I just started using Kubernetes and have been poking around on figuring out how to configure it to create new pods whenever a user connects

**Comment by naisanza** [comment]
@jdeathe How would you handle multiple users connecting to each of their own ssh containers without assigning a unique port for each user?

**Comment by jdeathe** [comment]
@naisanza - Either you need to use unique ports or use a unique IP address which is how it's done in Kubernetes and docker-compose (if you include an internal network + proxy container). Kubernetes creates a proxy in front of the services for you and gives you end-point URLs. The idea is that you can just scale out more containers behind the proxy so the containers are intended to all have the same configuration for a single app/service. 

If you want unique configuration per container/pod then you will need to define each container's (app in Kubernetes) configuration as it cannot be changed after first creating/running the container.

**Comment by jdeathe** [comment]
@naisanza - It might not meet your requirements but a possible way if, you have a single docker host, is to add users to the host with their own public keys and then modify their public key so it is prefixed with a command to run a container on the host (you could create your own script to start the container etc). In the following example it uses `nsenter` which can now be replaced with `docker exec -it {container-name} bash`. You could create a container for each user using their username for the container name and a named volume to persist their data if required.

https://github.com/jdeathe/centos-ssh/blob/2.2.0/command-keys.md

With this approach you don't need to care about the port number or IP address, (or the `SSH_USER`), of the container assuming you don't need it to have any published ports that are public facing.
