### ISSUE TITLE
DBUS_ERROR

### ISSUE THREAD

**Issue by lbbboy** [jdeathe/centos-ssh#474]
Failed to get D-Bus connection: Operation not permitted
Error: DBUS_ERROR: Failed to connect to socket /var/run/dbus/system_bus_socket:                                                                                                                               No such file or directory

**Comment by jdeathe** [comment]
@lbbboy There's not enough detail in your issue report to allow anyone to replicate it.

I suspect you are attempting to use systemd to run a process, (which is not available in the CentOS-7 based container), when you need to make use of supervisor to run any foreground processes.
