### ISSUE TITLE
When I try to connect it says that there is no supported authentication method available

### ISSUE THREAD

**Issue by jdeathe** [jdeathe/centos-ssh#475]
Question received via https://hub.docker.com/r/jdeathe/centos-ssh/ from **jesk**

> Hello, I am facing a problem with docker-compose...
> 
> I tried to create a new user using the environmental variables...
> ssh.pool-1.1.1:
> image: "jdeathe/centos-ssh:centos-7"
> container_name: "ssh.pool-1.1.1-test"
> ports:
> 
> "2020:22"
> volumes:
> /data/test:/home/test
> environment:
> SSH_USER: test
> SSH_USER_PASSWORD: test
> SSH_USER_HOME: /home/test
> SSH_USER_SHELL: /bin/bash
> When I try to connect it says that there is no supported authentication method available...
> Any idea?
> Thanks!

**Comment by jdeathe** [comment]
The `SSH_USER_PASSWORD` is only necessary if requiring a password when using `sudo`.

To connect via SSH requires the use of a public/private key pair - follow the instructions in the README for how to do this.


> Download the insecure private key and set permissions to 600.
> ```
> $ curl -LSs \
>   https://raw.githubusercontent.com/mitchellh/vagrant/master/keys/vagrant \
>   > id_rsa_insecure
> $ chmod 600 id_rsa_insecure
> ```
> Connect using the ssh command line client with the insecure private key.
> ```
> $ ssh -p 2020 -i id_rsa_insecure \
>   app-admin@{docker-host-ip}  
> ```

**Comment by naisanza** [comment]
@jdeathe It appears I'm still getting the permission denied, but works just fine with `rastasheep/ubuntu-sshd` docker image. It's a 4096 bit RSA key that I'm testing with.

```
Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
```

**Comment by jdeathe** [comment]
@naisanza Please provide steps on how to reproduce the issue? Are you setting your public key using the environment variable; without doing so it will be the vagrant insecure public key and not your own. Make sure to pull/use the latest release tag and not simply “:latest”

**Comment by naisanza** [comment]
@jdeathe I have a volume with `.ssh/authorized_keys` inside of it, mounted to `/root`

Using the environment variable, does it add it to `.ssh/authorized_keys`?

When I added the public key with the environment variable with no volumes mounted, it didn't allow me to login either. So I thought it was the format of my rsa key, which I've seen happen before

**Comment by jdeathe** [comment]
@naisanza Yes, I would not recommend mounting a volume over the container user's ~/.ssh/authorized_key as it will likely result in incorrect permissions; that is the purpose of [`SSH_AUTHORIZED_KEYS`](https://github.com/jdeathe/centos-ssh#ssh_authorized_keys).

**Comment by naisanza** [comment]
@jdeathe it works pretty well, and the permissions are good as well.

But I tried it both mounted, and not mounted, and neither methods works

**Comment by jdeathe** [comment]
@naisanza To help you any further you would need to provide a test case to reproduce your issue.

Without any information on how you are running the container I can only guess.

1. Do not mount the user's `~/.ssh/authorized_key directory` - this **will** cause unexpected issues.
2. Set your public key with `SSH_AUTHORIZED_KEYS` - Noting that environment variables will only take affect when the container is first created.
3. Log in with the correct user `SSH_USER` - defaults to `app-user`.
4. Use your private key to log in using the `-i` parameter of ssh - along the lines of: `ssh -p {container_port} -i {private_key_path} {SSH_USER}@{container_host}`.

To clarify how this works there is a [test case](https://github.com/jdeathe/centos-ssh/blob/2.3.0/test/shpec/operation_shpec.sh#L521-L595) which [covers the use of a custom public key](https://github.com/jdeathe/centos-ssh/blob/2.3.0/test/shpec/operation_shpec.sh#L552-L568)

**Comment by naisanza** [comment]
@jdeathe it was #3, I assumed it defaulted to `root`, since the default vagrant private key is public, and the default password is world readable in `/var/log/secure`, it seemed more like obfuscation

Is there a way to change the idle timeout? I'm not sure if it's your config, or rancher causing the connection to close

**Comment by jdeathe** [comment]
@naisanza Set your own sudo password or configure passwordless sudo to prevent needing the generated password in the containers logs. Details are in the README.

I’ve not experienced any timeout issues and I don’t have experience with Rancher to advise. Maybe you’re ssh client has a setting for keeping the connection alive.
