### ISSUE TITLE
where is the password for root，couldn't find in “docker logs”

### ISSUE THREAD

**Issue by imshi** [jdeathe/centos-ssh#562]
SSH Details
--------------------------------------------------------------------------------
user : app-admin
password : DQvz4xfpilVTjIkT
id : 500:500
home : /home/app-admin
chroot path : N/A
shell : /bin/bash
sudo : ALL=(ALL) ALL
key fingerprints :
dd:3b:b8:2e:85:04:06:e9:ab:ff:a8:0a:c0:04:6e:d6 (insecure key)
rsa host key fingerprint :
1a:d1:08:74:83:59:96:09:43:cf:f0:8f:7f:0a:a9:1f

**Comment by git-shine** [comment]
su or sudo can not be execute with DQvz4xfpilVTjIkT

**Comment by imshi** [comment]
need to use sudo -i

**Comment by jdeathe** [comment]
Hi @git-shine 

Thanks for your interest; happy to see you figured this out.

An example connection command is documented in the [README.md](https://github.com/jdeathe/centos-ssh#connect-to-the-running-container-using-ssh) but it's right at the end.

> To connect to the running container use:

```
$ ssh -p {container-port} \
  -i ~/.ssh/id_rsa_insecure \
  app-admin@{docker-host-ip} \
  -o StrictHostKeyChecking=no
```

The `root` use is disabled intentionally, as is password only access. As per the example, you need to use a private key for authentication. If you are running the container on a public facing network you must set your own public key using the environment variable `SSH_AUTHORIZED_KEYS `(https://github.com/jdeathe/centos-ssh#ssh_authorized_keys) or risk exposing your container to unauthorised access.

Please let me know if you require any additional clarification or assistance?

**Comment by imshi** [comment]
thx, everything seems to work fine now.
